language: node_js
node_js:
- '0.10'
before_install:
- npm install coffee-script
before_script:
- ./node_modules/.bin/cake archive
script:
- ./node_modules/.bin/cake test
deploy:
  provider: releases
  api_key:
    secure: "G5qOd4sFhTdDx0Y6+Yo+UALLklK+uXw58bpk/xWwmwetVme5H1fIprF98oBgV/AA3h1WS7NGm9UZ/gJjka4E5x08VLogMGv5W9UVYi7SjzRlOUaFTn/sb3R30KyFxMDKnuNBPGi8759ojgB5jt7ZLDl/9uQNamrone4im+yxnRI="
  file: build/APIBlueprintGenerator.zip
  skip_cleanup: true
  on:
    tags: true
    repo: luckymarmot/Paw-APIBlueprintGenerator
